
MY_AWS_SECRET = "AKIALALEMEL33EEXAMPLE"
MY_AWS_SECRET = "AKIALALEMEL33EEXAMPLE"
MY_AWS_SECRET = "AKIALALEMEL33EEXAMPLE"
MY_AWS_SECRET = "AKIALALEMEL33EEXAMPLE"
MY_AWS_SECRET = "AKIALALEMEL33EEXAMPLE"
MY_AWS_SECRET = "AKIALALEMEL33EEXAMPLE"
MY_AWS_SECRET = "AKIALALEMEL33EEXAMPLE"
