another_var = "a"
aws_secret = "AKIAIMNOJVGFDXXXE4OB"






self.logs += os.popen(f"git remote add origin {self.repo_instance.ssh_url}").read()
another_var = "a"
another_var = "a"
another_var = "a"
another_var = "a"
another_var = "a"
another_var = "a"
another_var = "a"
another_var = "a"
another_var = "a"

another_var = "a"
another_var = "a"
another_var = "a"
another_var = "a"
another_var = "a"
another_var = "a"
another_var = "a"
another_var = "a"
another_var = "a"

another_var = "a"
another_var = "a"
another_var = "a"
another_var = "a"
another_var = "a"
another_var = "a"
another_var = "a"
another_var = "a"
another_var = "a"

another_var = "a"
another_var = "a"
another_var = "a"
another_var = "a"
another_var = "a"
another_var = "a"
another_var = "a"
another_var = "a"
another_var = "a"

another_var = "a"
another_var = "a"
another_var = "a"
another_var = "a"
another_var = "a"
another_var = "a"
another_var = "a"
another_var = "a"
another_var = "a"
another_var = "a"
another_var = "a"
another_var = "a"
another_var = "a"
another_var = "a"
another_var = "a"
another_var = "a"
another_var = "a"
another_var = "a"
another_var = "a"
another_var = "a"
another_var = "a"
another_var = "a"
another_var = "a"
another_var = "a"
another_var = "a"
another_var = "a"
another_var = "a"
another_var = "a"
another_var = "a"
another_var = "a"
another_var = "a"
another_var = "a"
another_var = "a"
another_var = "a"
another_var = "a"
another_var = "a"
