a = 1
aws_secret1 = "AKIAIMNOJVGFDXXXE4OC"aws_secret1 = "AKIAIMNOJVGFDXXXE4OC"aws_secret1 = "AKIAIMNOJVGFDXXXE4OC"
aws_secret1 = "AKIAIMNOJVGFDXXXE4OC"
aws_secret1 = "AKIAIMNOJVGFDXXXE4OC"
aws_secret1 = "AKIAIMNOJVGFDXXXE4OC"
aws_secret1 = "AKIAIMNOJVGFDXXXE4OC"
aws_secret1 = "AKIAIMNOJVGFDXXXE4OC"

