provider:
  name: aws
  runtime: nodejs14.x
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:*"  # Overly permissive action, shou
        ld be more specific
      Resource: 
        - "*"    # Overly permissive resource, should be more specific

functions:
  hello:
    handler: handler.hello
    environment:
    
      DB_PASSWORD: "mySuperSecretPassword"  # Hard-coded sensitive data
    layers:
      - arn:aws:lambda:us-east-1:123456789012:layer:your-layer-name:1
    tracing: false  # Disabling X-Ray tracing (should be enabled for better monitoring)

resources:
  Resources:
    MyBucket:
      Type: "AWS::S3::Bucket"
      Properties:
        BucketName: "my-plain-bucket"
        PublicAccessBlockConfiguration:
          BlockPublicAcls: false  # Public ACLs should be blocked
          BlockPublicPolicy: false # Public policies should be blocked
